---
- name: Software uninstallation
  hosts: slave1
  tasks:
    - name: stop nginx service
      service:
            name: nginx
            state: stopped
    - name: uninstall nginx
      apt:
           name: nginx
           state: absent
           autoremove: true
           purge: true